#!/usr/local/bin/zsh
print "Brew updating"
brew update
brew upgrade
print "node updating"
sudo n latest
print "NPM updating"
sudo npm update -g
sudo npm upgrade -g
print "PIP updating"
sudo pyUp
print "Gem updating"
sudo gem update
print "tldr updating"
tldr --update

print "finished"
exit
