#!/usr/local/bin/zsh
print "Brew updating"
brew update
brew upgrade

print "NPM updating"
npm update -g
npm upgrade -g
print "PIP updating"
pyUp
print "Gem updating"
gem update
print "tldr updating"
tldr --update
print "finished"
exit
